=head1 NAME

rsleep - an executable which provides random sleep for scripts

=head1 SYNOPSIS

rsleep [-d] [NUMBER]
rsleep -v
rsleep -h

=head1 DESCRIPTION

Pause for a random period between 0 and NUMBER seconds.

[NUMBER] 
-d   debug
-v   displays version
-h   displays help

=head1 EXAMPLES

rsleep    ; echo "do something a bit later"
rsleep 60 ; echo "do something from crontab randomly in the minute"

=head1 AUTHOR

Written by Michael R. Davis

=head1 COPYRIGHT

Copyright (c) 2013-2025 Michael R. Davis, License GPLv2

=head1 SEE ALSO

sleep(1)
